---
title: "Week 2"
format: html
description: first quiz, packages, objects, verbs, census, etc...
date: 2026-09-04
---

# What We Did
# week 2

- Advice for acing the weekly quiz
    - retype notes and code
- Always open up project file not individual files to edit, you can open them up individually in R
- Build → Render Website (entire site runs with new changes)
- console: code not saved
- R script: code chunk lives inside .qmd
- result ← filter (counties, population> 500000)
    - object that holds the result ← (assignment) that the function (verb) applies arguments towards the input data

## packages

- install.packages(”dplyr”)
    - only needs to be done once
- library(dplyr)
    - do every time u wanna use it
- data frame (table)
    - every row is an observation
    - every column is a variable
    - for dplyr, tibble is a df that prints nicer

| NAME | INCOME | MOE |
| --- | --- | --- |
| Adams | 45678 | 9989 |
| Berks | 567890 | 9876 |
| Bucks | 3456789 | 2345 |
- what dplyr does
    - tibble → verb → tibble

## verbs

- filter(): picks rows
- select(): picks columns
- mutate(): add a new computed column
- arrange():  change the order of rows (asc, desc)
- group_by() + summarize(): many rows become few

Step 1.

filter(counties, moe_pct>10)

Step 2.

arrange(Step1, desc(moe_pct))

Step 3.

select(NAME, moe_pct)

- Want to write “and then”?
    - %>% or |> : strings functions without saving an intermediate file along the way like steps 1-3.

Steps 1-3 become:

```jsx
new_data ← counties %>%
	filter(moe_pct) %>%
	arrange(desc(moe_pct))%>%
	select(NAME, moe_pct)
```

takes input (counties) and applies these functions at once into a single

## census data

Decennial Census

- 10 years
- 10 questions
- long form

American Community Survey (ACS)

- 2005
- 3% of households are surveyed on income, commute, ethnicity, rent, etc..
- Results in an **estimate** for the population
- 1-year ACS conducted in places > 65,000 people (data available and current at metropolitan level)
- 5-year ACS (block groups and census tracts)
    - each year represents a 5-year average
    - estimate +- a margin of error (MOE)

**B1234_001E**

B is the Base table

1234 is the table number

001E is the Line number

E is the Estimate

M is the MOE

load_variables()

**state** → **county** → **tract** (neighborhood of 5-8,000 people and boundaries change frequently)

**GEOID**

42101000100

42 is the state

101 is the county

000100 is the tract (11 digits)

block groups is the 12th

- always stored as string
- make sure u check the way its stored before trying to do anything with it

# exercise

data ← get_acs(geography = “county”,

variables = c(”B19013_001”,

“B10103_001”),

state=”PA”, year = 2023, survey = “acs5”)

tidy (long) → wide by doing output = “wide”

FILTE**R** IS ROWS

SELE**C**T IS COLUMNS

# Reflection
Enjoyed the quiz more than I thought.

# Questions I still have 
