{
  "hash": "d77d90e3e1d14790b4d4d4409146e692",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Chloe Alimurong\"\ndate: 2026-09-07\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n---\n\n## The question\n\n**In this analysis, I look at median home values across counties in Maryland, and ask which communities we measure most and least reliably. I am interested in seeing the trends over time, especially before and after COVID and counties with more urban areas. Or, if there's a trend amongst demographics such as having a Bachelors degree. I wonder if there's data in specific communities that's least reliable and if I can find potential explanations in those discrepancies.**\n\n---\n\n## Choosing what to measure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"MD\"        \nmy_variable <- \"B25077_001\"     # Median home value\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 24  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                          variable   estimate   moe\n  <chr> <chr>                         <chr>         <dbl> <dbl>\n1 24001 Allegany County, Maryland     B25077_001   149200  5832\n2 24003 Anne Arundel County, Maryland B25077_001   450300  4485\n3 24005 Baltimore County, Maryland    B25077_001   330000  3148\n4 24009 Calvert County, Maryland      B25077_001   440200  8554\n5 24011 Caroline County, Maryland     B25077_001   272400  7506\n6 24013 Carroll County, Maryland      B25077_001   406400  7074\n```\n\n\n:::\n:::\n\n\n**I got 6 rows and there are 24 counties in MD, the row count does not match because I just printed the head (default first 6 rows) so I used print(county_data) and checked there are truly 24 rows.**\n\n---\n\n## How big is the margin of error?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                          estimate   moe moe_pct\n   <chr>                            <dbl> <dbl>   <dbl>\n 1 Somerset County, Maryland       164300 14949    9.10\n 2 Kent County, Maryland           307100 17782    5.79\n 3 Garrett County, Maryland        217000 10296    4.74\n 4 Dorchester County, Maryland     252300 11410    4.52\n 5 Talbot County, Maryland         398300 16471    4.14\n 6 Allegany County, Maryland       149200  5832    3.91\n 7 Worcester County, Maryland      348100 12766    3.67\n 8 Cecil County, Maryland          311800  8842    2.84\n 9 Caroline County, Maryland       272400  7506    2.76\n10 Queen Anne's County, Maryland   441800 10627    2.41\n```\n\n\n:::\n:::\n\n\n**The county with the largest margin of error relative to its estimate is Somerset county at 9.1% MOE, making it the least reliable county in MD for my variable.**\n\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 1  ~ \"High confidence\",\n    moe_pct < 5 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence     4\n2 Low confidence      2\n3 Moderate           18\n```\n\n\n:::\n:::\n\n\n**4 counties in MD fall into the 'High' confidence category. 18 fall into the 'Moderate' confidence category. 2 fall into the 'Low' confidence category. I rearranged the threshold to be 1% for high confidence and 5% for moderate since my state is small and there are counties with an even smaller population so they mostly fell into high confidence. **\n\n---\n\n## Is the margin of error bigger in small places?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                          myvarE myvarM   popE  popM\n  <chr> <chr>                          <dbl>  <dbl>  <dbl> <dbl>\n1 24001 Allegany County, Maryland     149200   5832  67762    NA\n2 24003 Anne Arundel County, Maryland 450300   4485 590936    NA\n3 24005 Baltimore County, Maryland    330000   3148 849586    NA\n4 24009 Calvert County, Maryland      440200   8554  93791    NA\n5 24011 Caroline County, Maryland     272400   7506  33406    NA\n6 24013 Carroll County, Maryland      406400   7074 174318    NA\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 1  ~ \"High confidence\",\n    moe_pct < 5 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence          4        863423 \n2 Low confidence           2         21975 \n3 Moderate                18        148505.\n```\n\n\n:::\n:::\n\n\n**The average population of high-confidence counties is 863,423 people. The low-confidence counties has an average of  21,975 people while the moderate averages at 148,506 people. This pattern tells us that the greater the average population, the greater likelihood of a higher margin of error is for the median home value variable.**\n\n---\n\n## What this means for policy\n\n**As a MD resident, this makes sense that the counties we know the least about/have less accurate information on, are the counties with smaller populations. Somerset county has the highest MOE at 9.1%, I don't really know anyone from there, nor Kent (5.8%) or Garrett (4.7%) county, the top 2 and 3 for highest MOE. These are counties with wild horses, other wildlife, and beaches. The counties we pass through on our way to Ocean City where you can't really see houses. Somerset county, MD is one of the few counties in the Northeastern-ish US that only recently needed fiber (internet cable) built to. Basically, not a lot of people live there. Not enough to have a significant statistics on median home value. This is likely because of sampling variability in results we can't account for in small counties. ACS is a survey of a sample so bigger counties like Baltimore and Montgomery would receive more responses to the survey than a small one like Somerset. There could be a really expensive or really cheap house that could be skewing the data that adds to statistical uncertainty in a small county. For state agencies studying the variable, median home value, smaller counties would be at a disadvantage. For example, if a state agency wants to allocate funding such as decreasing or increasing the construction of affordable housing units or even discounting/increasing APR for homeowner loans, residents of these smaller counties that need funding would be left out since the data likely misrepresented them or left them out completely. For example, Somerset county's estimated median home value is $164,300, for those looking to move to Somerset county, they wouldn't receive much assistance as the predicted value is lower than most counties in MD.**\n\n---\n\n## Optional challenges - For those craving more\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Propagate the margin of error\n\ncounty_summary <- county_data %>% \n  summarize(\n    sum_est = sum(estimate),\n    sum_moe = moe_sum(moe, estimate)\n    #sum_prop = moe_prop()\n  )\n\nprint(county_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  sum_est sum_moe\n    <dbl>   <dbl>\n1 8417700  44123.\n```\n\n\n:::\n\n```{.r .cell-code}\n## Parameterize the report.\n\n## Write a function and iterate.\n\n\n## Change the geographic scale.\n```\n:::\n\n\n---\n\n## Before you submit\n\n::: {.callout-note}\n## Delete this box — checklist\n- [ ] **Session → Restart R**, then render the whole project. It works.\n- [ ] Committed and pushed\n- [ ] You opened your live site and looked at the published page\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}